---
title: "Trees"
author: "Gökce Ergün"
date: "2/3/2021"
output: html_document
---
Hello world

Libraries that are used
```{r}
#install.packages('dplyr')
library(dplyr)
#install.package('lubridate')
library(lubridate)
```



Reading the data
```{r}
df_trees <- read.csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-28/sf_trees.csv')
```


Look at the data structure

```{r}
str(df_trees)
```

The data type of date column is changed. 
```{r}
df_trees$date <- as.POSIXlt(df_trees$date,format="%Y-%m-%d")
```

```{r}
class(df_trees$date)
```


save the planted year of the tree as a separate column

```{r}
df_trees$year <- year(df_trees$date) ## year function is from lubridate package
```


```{r}
df_trees %>%
  select(year)%>%
  arrange(year) %>%
  head(n=5)
  
```


Check the percentage of the complete cases in each column

```{r}
for (col in colnames(df_trees)){
  print(paste(col, "=", mean(complete.cases(df_trees[[col]]))))
}
```



Get the number of unique species
```{r}
length(unique(df_trees$species))
```


```{r}
head(unique(df_trees$species))

```

Separate the species column into two
```{r}
df_trees <- separate(df_trees, species, sep = " :: ", remove = FALSE, into = c('species_lat, species_nor'))
```



